version: '3.8'

services:
  webserver:
    container_name: jira-data-collector
    image: jira-data-collector
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - .env
    #environment:
    #  - DB_HOST: ${DB_HOST}
    #  - DB_USER: ${DB_USER}
    #  - DB_PASSWORD: ${DB_PASSWORD}
    #  - DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/jira_data"
    #  - JIRA_URL: ${JIRA_URL}
    #  - JIRA_USER: ${JIRA_USER}
    #  - JIRA_TOKEN: ${JIRA_TOKEN}
    #  - JIRA_PROJECTS: ${JIRA_PROJECTS}
    #  - JIRA_MAX_RESULT: ${JIRA_MAX_RESULT}
    command: ["/Users/wegelpi/supervisord", "-c", "/Users/wegelpi/supervisor/conf.d/supervisord.conf"]
    #depends_on:
    #  - []

  #db:
  #  image: postgres:16
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  environment:
  #    - POSTGRES_USER=user
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_DB=mydatabase

#volumes:
#  postgres_data: